### ISSUE TITLE
Does not work with the new NZ line.

### ISSUE THREAD

**Issue by expattaxtools** [bezmi/jvc_projector#11]
The new JVC NZ line requires a password in addition to the IP address to execute commands.

**Comment by iloveicedgreentea** [comment]
As it happens, I just remade/refactored/wrote a library which supports NZ https://github.com/iloveicedgreentea/jvc_projector_improved

There is also a home assistant component here. https://github.com/iloveicedgreentea/jvc_homeassistant

Both tested on my NZ7 just make sure you have your password set on your NZ first.

**Comment by bezmi** [comment]
Apologies for the radio slience, I have been very busy as of late. Before that I was working on a big refactor in the develop branch to make it work with async (and non async).

On the homeassistant component side of things, the develop branch has a (mostly) working config_flow implementation and should be more robust (needs a bit of testing to pick up edge cases, etc).

@iloveicedgreentea if you have time, it would be great to have a single unified JVC projector library/component. Please have a look at the develop branches and try to implement your changes and comments. I'm happy to put anyone willing to help with upkeep as a co-author of the project. If you don't have time, that's understandable. When I pick up development on this project again, I'll be sure to implement your adjustments for the NZ series protocol.
