### ISSUE TITLE
Automate build and release using GitHub actions

### ISSUE THREAD

**Issue by piejanssens** [bezmi/jvc_projector#21]
https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/

**Comment by bezmi** [comment]
Reopening because it's a good idea and not yet complete. Pushing a new version simultaneously to pypi and also as a github release when a corresponding tag is committed would be quite a useful action if possible.

**Comment by bezmi** [comment]
completed with bezmi/jvc_projector@c6552b8
