### ISSUE TITLE
power on command timing

### ISSUE THREAD

**Issue by chuba2** [bezmi/jvc_projector#3]
Hi,

I tried your code with JVC DLA-X30B.

All worked accept the Power On command. After some debugging, I inserted 1 second delay after sending the power on command and I had to send 3 of these in a row from my script. WIth that, all finally worked. I have 4 separate scripts that work on the same code that you provide + my delay after the sendall command of 1 second. The 3 scripts of power off, status, and model inquiry work as is. The power on command works only if I send it 3 times in a row. I would hope to figure out what the timing issue is but may need your help.

**Comment by bezmi** [comment]
I've got around to this a little late, so apologies for that. So I have similar problems with timing on my X5900, where it takes 600-700ms before a command is accepted by the projector. Some commands seem to have a smaller delay than others, so it might just be that you need to wait a little longer for the power on command. Have you tried increasing the delay for the power on command?

**Comment by bezmi** [comment]
There is now a global delay setting for the `__init__` function.
