### ISSUE TITLE
New set of Commands to be added

### ISSUE THREAD

**Issue by sroelens** [bezmi/jvc_projector#4]
Hi,

I am looking for the cursor commands to navigate in the menu via external commands, I do not see it in the documentation, anyone knows these?

LEFT
RIGHT
UP
DOWN
OK
BACK

**Comment by sroelens** [comment]
Found them, would it be possible to add these into your package?

High Lamp = b"\x21\x89\x01\x50\x4D\x4C\x50\x31\x0A"
Low  Lamp = b"\x21\x89\x01\x50\x4D\x4C\x50\x30\x0A"
2D        = b"\x21\x89\x01\x49\x53\x33\x44\x30\x0A"
Auto      = b"\x21\x89\x01\x49\x53\x33\x44\x31\x0A"
3D SBS    = b"\x21\x89\x01\x49\x53\x33\x44\x33\x0A"
Menu      = b"\x21\x89\x01\x52\x43\x37\x33\x32\x45\x0A"
Down      = b"\x21\x89\x01\x52\x43\x37\x33\x30\x32\x0A"
Left      = b"\x21\x89\x01\x52\x43\x37\x33\x33\x36\x0A"
Right     = b"\x21\x89\x01\x52\x43\x37\x33\x33\x34\x0A"
Up        = b"\x21\x89\x01\x52\x43\x37\x33\x30\x31\x0A"
OK        = b"\x21\x89\x01\x52\x43\x37\x33\x32\x46\x0A"
Back      = b"\x21\x89\x01\x52\x43\x37\x33\x30\x33\x0A"

**Comment by sroelens** [comment]
Spaces replace with Underscore:

high_lamp = b"\x21\x89\x01\x50\x4D\x4C\x50\x31\x0A"
low_lamp = b"\x21\x89\x01\x50\x4D\x4C\x50\x30\x0A"
2D        = b"\x21\x89\x01\x49\x53\x33\x44\x30\x0A"
Auto_3D      = b"\x21\x89\x01\x49\x53\x33\x44\x31\x0A"
3D_SBS    = b"\x21\x89\x01\x49\x53\x33\x44\x33\x0A"
menu      = b"\x21\x89\x01\x52\x43\x37\x33\x32\x45\x0A"
down      = b"\x21\x89\x01\x52\x43\x37\x33\x30\x32\x0A"
left      = b"\x21\x89\x01\x52\x43\x37\x33\x33\x36\x0A"
right     = b"\x21\x89\x01\x52\x43\x37\x33\x33\x34\x0A"
up        = b"\x21\x89\x01\x52\x43\x37\x33\x30\x31\x0A"
OK        = b"\x21\x89\x01\x52\x43\x37\x33\x32\x46\x0A"
back      = b"\x21\x89\x01\x52\x43\x37\x33\x30\x33\x0A"

**Comment by bezmi** [comment]
It is definitely possible for them to be added, but I have very limited time. There is a guide in the README that goes over adding commands, so if you need them ASAP, you can look at following that.

**Comment by bezmi** [comment]
The menu commands have been added.
