### ISSUE TITLE
Version Key Required

### ISSUE THREAD

**Issue by jtroberts1** [bezmi/jvc_projector#7]
To prevent future HA upgrades from breaking this great component, can you add the version as shown in the error below?

PS: Thanks for creating this.  Absolutely fantastic!

_No 'version' key in the manifest file for custom integration 'jvcprojector'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'jvcprojector'
11:54:58 AM – loader.py (WARNING)_

**Comment by bezmi** [comment]
This was an issue with the hass custom component, not this module itself. Should be fixed now.
